version: '3.3'
services:

  redis:
    image: redis:latest

  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django

  django: &base_container
    image: test/django-blog:latest
    ports:
      - "8000:8000"
    volumes:
     - ./:/app/
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    command: |
      python manage.py runserver 0.0.0.0:8000

  worker:
    <<: *base_container
    ports: [ ]
    command: |
      python manage.py rqworker default
  
