name: Django Checks

on:
  push:
    branches:
      - master

jobs:
  checks:

    name: Run Django checks

    runs-on: ubuntu-latest

    services:

      redis:
        image: redis:4.0.14
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      DJANGO_SETTINGS_MODULE: blog.settings_test

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for missing migrations
        run: |
          python manage.py makemigrations --dry-run --check --verbosity=3

      - name: Run Linter checks
        run: |
          flake8 .
          isort .
          black .

      - name: Run Pytest suite
        run: |
          pytest --create-db --disable-warnings
        env:
          REDIS_URL: redis://localhost:${{ job.services.redis.ports[6379] }}